# Generated by Django 6.0 on 2026-01-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appointment_meet_link_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticsession',
            name='grad_cam_image',
        ),
        migrations.RemoveField(
            model_name='diagnosticsession',
            name='lab_report',
        ),
        migrations.RemoveField(
            model_name='diagnosticsession',
            name='shap_plot_image',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosticsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Analysis Running'), ('completed', 'AI Result Ready'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
