# Generated by Django 6.0 on 2026-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='awards_text',
            field=models.TextField(blank=True, help_text='Comma separated awards'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='education_text',
            field=models.TextField(blank=True, help_text='Comma separated degrees'),
        ),
    ]
