import React from "react";
import { FileText, Video, Microscope, Stethoscope } from "lucide-react";

const ServicesSection = () => {
  return (
    <section id="services" className="py-24 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col lg:flex-row items-center gap-16">
          <div className="w-full lg:w-1/2">
            <h2 className="text-3xl md:text-4xl font-extrabold text-gray-900 mb-8">
              End-to-End Clinical Pipeline
            </h2>
            <div className="space-y-10">
              <div className="flex gap-6">
                <div className="flex-shrink-0">
                  <div className="flex items-center justify-center h-14 w-14 rounded-2xl bg-blue-50 text-blue-600">
                    <Microscope className="h-7 w-7" />
                  </div>
                </div>
                <div>
                  <h4 className="text-lg font-bold text-gray-900 mb-2">
                    Multimodal Data Ingestion
                  </h4>
                  <p className="text-gray-500 leading-relaxed">
                    Support for DICOM (MRI), structured JSON lab exports, and
                    PDF reports. Pre-processing includes skull stripping and
                    intensity normalization.
                  </p>
                </div>
              </div>

              <div className="flex gap-6">
                <div className="flex-shrink-0">
                  <div className="flex items-center justify-center h-14 w-14 rounded-2xl bg-blue-50 text-blue-600">
                    <FileText className="h-7 w-7" />
                  </div>
                </div>
                <div>
                  <h4 className="text-lg font-bold text-gray-900 mb-2">
                    GenAI Reporting
                  </h4>
                  <p className="text-gray-500 leading-relaxed">
                    Automated PDF generation with patient-friendly explanations
                    generated by constrained LLMs, summarizing risk scores and
                    next steps.
                  </p>
                </div>
              </div>

              <div className="flex gap-6">
                <div className="flex-shrink-0">
                  <div className="flex items-center justify-center h-14 w-14 rounded-2xl bg-blue-50 text-blue-600">
                    <Stethoscope className="h-7 w-7" />
                  </div>
                </div>
                <div>
                  <h4 className="text-lg font-bold text-gray-900 mb-2">
                    Rule-Based Medicine
                  </h4>
                  <p className="text-gray-500 leading-relaxed">
                    Evidence-based therapy suggestions (e.g., Corticosteroids,
                    IVIG) based on clinical criteria guidelines, ready for
                    doctor verification.
                  </p>
                </div>
              </div>

              <div className="flex gap-6">
                <div className="flex-shrink-0">
                  <div className="flex items-center justify-center h-14 w-14 rounded-2xl bg-blue-50 text-blue-600">
                    <Video className="h-7 w-7" />
                  </div>
                </div>
                <div>
                  <h4 className="text-lg font-bold text-gray-900 mb-2">
                    Global Doctor Network
                  </h4>
                  <p className="text-gray-500 leading-relaxed">
                    Synchronous video consultations and asynchronous text triage
                    with verified specialists.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="w-full lg:w-1/2">
            <div className="bg-gradient-to-br from-gray-900 to-blue-900 rounded-3xl p-8 h-[500px] flex items-center justify-center relative overflow-hidden shadow-2xl">
              <div
                className="absolute inset-0 bg-cover opacity-20 mix-blend-overlay"
                style={{
                  backgroundImage:
                    "url('https://images.unsplash.com/photo-1579684385127-1ef15d508118?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80')",
                }}
              ></div>
              <div className="relative z-10 text-center text-white max-w-sm">
                <div className="w-24 h-24 bg-white/10 backdrop-blur-sm rounded-full flex items-center justify-center mx-auto mb-6 border border-white/20">
                  <Microscope className="h-10 w-10 text-blue-300" />
                </div>
                <h3 className="text-3xl font-bold mb-4">Patient-Doctor Loop</h3>
                <p className="text-blue-200 leading-relaxed">
                  From symptom entry to AI Analysis, followed by specialist
                  review and final prescription—all in one secure dashboard.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ServicesSection;
