import React, { useState } from "react";
import {
  FileText,
  Video,
  Microscope,
  Stethoscope,
  CheckCircle2,
  UploadCloud,
  BrainCircuit,
  Activity,
  ArrowRight,
} from "lucide-react";

const ServicesSection = () => {
  const [activeService, setActiveService] = useState(0);

  const services = [
    {
      id: 0,
      title: "Multimodal Data Ingestion",
      desc: "Support for DICOM (MRI), structured JSON, and PDF reports with auto-normalization.",
      icon: <Microscope className="h-6 w-6" />,
      color: "from-cyan-400 to-blue-500",
      bg: "bg-cyan-50",
      text: "text-cyan-600",
    },
    {
      id: 1,
      title: "GenAI Reporting",
      desc: "Patient-friendly PDFs generated by constrained LLMs, summarizing risk scores.",
      icon: <BrainCircuit className="h-6 w-6" />,
      color: "from-purple-400 to-pink-500",
      bg: "bg-purple-50",
      text: "text-purple-600",
    },
    {
      id: 2,
      title: "Rule-Based Medicine",
      desc: "Evidence-based therapy suggestions (Corticosteroids, IVIG) awaiting verification.",
      icon: <Stethoscope className="h-6 w-6" />,
      color: "from-emerald-400 to-teal-500",
      bg: "bg-emerald-50",
      text: "text-emerald-600",
    },
    {
      id: 3,
      title: "Global Doctor Network",
      desc: "Synchronous video consultations and asynchronous text triage with specialists.",
      icon: <Video className="h-6 w-6" />,
      color: "from-amber-400 to-orange-500",
      bg: "bg-amber-50",
      text: "text-amber-600",
    },
  ];

  return (
    <section
      id="services"
      className="py-24 bg-slate-50 relative overflow-hidden"
    >
      {/* Background Decor */}
      <div className="absolute top-0 right-0 -translate-y-1/2 translate-x-1/2 w-96 h-96 bg-blue-200/40 rounded-full blur-3xl"></div>
      <div className="absolute bottom-0 left-0 translate-y-1/2 -translate-x-1/2 w-96 h-96 bg-purple-200/40 rounded-full blur-3xl"></div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="mb-16 text-center md:text-left">
          <h2 className="text-4xl md:text-5xl font-extrabold text-slate-900 mb-4 tracking-tight">
            End-to-End{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">
              Clinical Pipeline
            </span>
          </h2>
          <p className="text-lg text-slate-600 max-w-2xl">
            From raw data ingestion to specialist consultation, our pipeline
            automates the complex workflows of rare disease diagnosis.
          </p>
        </div>

        <div className="flex flex-col lg:flex-row gap-8 lg:gap-12 items-stretch">
          {/* --- LEFT SIDE: Navigation Cards --- */}
          <div className="w-full lg:w-5/12 space-y-4">
            {services.map((service, index) => (
              <div
                key={service.id}
                onMouseEnter={() => setActiveService(index)}
                className={`group relative p-6 rounded-2xl border transition-all duration-300 cursor-pointer overflow-hidden ${
                  activeService === index
                    ? "bg-white border-blue-200 shadow-xl scale-[1.02]"
                    : "bg-white/50 border-transparent hover:bg-white hover:border-slate-200"
                }`}
              >
                {/* Active Indicator Bar */}
                <div
                  className={`absolute left-0 top-0 bottom-0 w-1.5 transition-all duration-300 bg-gradient-to-b ${service.color} ${activeService === index ? "opacity-100" : "opacity-0"}`}
                />

                <div className="flex items-start gap-4">
                  <div
                    className={`flex-shrink-0 p-3 rounded-xl transition-colors duration-300 ${activeService === index ? service.bg + " " + service.text : "bg-slate-100 text-slate-400"}`}
                  >
                    {service.icon}
                  </div>
                  <div>
                    <h3
                      className={`text-lg font-bold mb-1 transition-colors ${activeService === index ? "text-slate-900" : "text-slate-600"}`}
                    >
                      {service.title}
                    </h3>
                    <p className="text-sm text-slate-500 leading-relaxed">
                      {service.desc}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* --- RIGHT SIDE: Dynamic Visual --- */}
          <div className="w-full lg:w-7/12 min-h-[500px]">
            <div className="relative h-full w-full bg-slate-900 rounded-3xl shadow-2xl overflow-hidden border border-slate-700 transition-all duration-500 flex flex-col">
              {/* Header of the Fake Interface */}
              <div className="flex items-center justify-between px-6 py-4 border-b border-slate-700/50 bg-slate-800/50 backdrop-blur-md">
                <div className="flex space-x-2">
                  <div className="w-3 h-3 rounded-full bg-red-500/80"></div>
                  <div className="w-3 h-3 rounded-full bg-yellow-500/80"></div>
                  <div className="w-3 h-3 rounded-full bg-green-500/80"></div>
                </div>
                <div className="text-xs font-mono text-slate-400 flex items-center gap-2">
                  <Activity
                    size={12}
                    className="animate-pulse text-green-400"
                  />
                  SYSTEM_ACTIVE
                </div>
              </div>

              {/* Dynamic Content Area */}
              <div className="relative flex-1 p-8 flex items-center justify-center bg-grid-white/[0.02]">
                {/* 1. DATA INGESTION VIEW */}
                <div
                  className={`absolute inset-0 p-8 flex flex-col justify-center transition-all duration-500 ${activeService === 0 ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8 pointer-events-none"}`}
                >
                  <div className="bg-slate-800/80 rounded-xl p-6 border border-slate-700 w-full max-w-md mx-auto">
                    <div className="flex items-center justify-between mb-6">
                      <span className="text-cyan-400 font-mono text-sm">
                        UPLOADING DICOM...
                      </span>
                      <span className="text-white font-bold">84%</span>
                    </div>
                    <div className="h-2 bg-slate-700 rounded-full overflow-hidden mb-6">
                      <div className="h-full bg-cyan-500 w-[84%] animate-[loading_2s_ease-in-out]"></div>
                    </div>
                    <div className="space-y-3">
                      {[1, 2, 3].map((i) => (
                        <div
                          key={i}
                          className="flex items-center gap-3 text-sm text-slate-300"
                        >
                          <CheckCircle2 size={16} className="text-green-500" />
                          <span>Sequence_T2_FLAIR_00{i}.dcm</span>
                        </div>
                      ))}
                    </div>
                  </div>
                  {/* Floating Icon */}
                  <UploadCloud className="absolute top-1/4 right-1/4 text-cyan-500/10 w-40 h-40 animate-pulse" />
                </div>

                {/* 2. GEN AI VIEW */}
                <div
                  className={`absolute inset-0 p-8 flex flex-col justify-center transition-all duration-500 ${activeService === 1 ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8 pointer-events-none"}`}
                >
                  <div className="bg-gradient-to-br from-purple-900/50 to-slate-900 border border-purple-500/30 rounded-xl p-6 w-full max-w-md mx-auto backdrop-blur-md">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="p-2 bg-purple-600 rounded-lg">
                        <BrainCircuit className="text-white w-5 h-5" />
                      </div>
                      <span className="text-white font-semibold">
                        AI Analysis Summary
                      </span>
                    </div>
                    <div className="space-y-2">
                      <div className="h-2 w-3/4 bg-slate-700 rounded animate-pulse"></div>
                      <div className="h-2 w-full bg-slate-700 rounded animate-pulse delay-75"></div>
                      <div className="h-2 w-5/6 bg-slate-700 rounded animate-pulse delay-150"></div>
                    </div>
                    <div className="mt-6 p-3 bg-purple-500/20 rounded border border-purple-500/30 text-purple-200 text-sm">
                      "High probability of Anti-NMDAR Encephalitis detected
                      based on limbic system hyperintensity."
                    </div>
                  </div>
                </div>

                {/* 3. RULE BASED VIEW */}
                <div
                  className={`absolute inset-0 p-8 flex flex-col justify-center transition-all duration-500 ${activeService === 2 ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8 pointer-events-none"}`}
                >
                  <div className="bg-slate-800 rounded-xl border border-emerald-500/30 w-full max-w-md mx-auto overflow-hidden">
                    <div className="bg-emerald-900/30 p-4 border-b border-emerald-500/20">
                      <h4 className="text-emerald-400 font-bold flex items-center gap-2">
                        <Stethoscope size={18} /> Recommended Protocol
                      </h4>
                    </div>
                    <div className="p-4 space-y-3">
                      <div className="flex items-center justify-between p-3 bg-slate-700/50 rounded-lg border border-slate-600">
                        <span className="text-slate-200 text-sm">
                          IV Methylprednisolone
                        </span>
                        <span className="px-2 py-1 bg-emerald-500/20 text-emerald-400 text-xs rounded font-bold">
                          High Match
                        </span>
                      </div>
                      <div className="flex items-center justify-between p-3 bg-slate-700/50 rounded-lg border border-slate-600">
                        <span className="text-slate-200 text-sm">
                          Plasma Exchange (PLEX)
                        </span>
                        <span className="px-2 py-1 bg-yellow-500/20 text-yellow-400 text-xs rounded font-bold">
                          Secondary
                        </span>
                      </div>
                    </div>
                    <div className="bg-slate-900 p-3 text-center">
                      <button className="text-xs text-emerald-500 hover:text-emerald-400 font-bold uppercase tracking-wider">
                        Verify with Specialist &rarr;
                      </button>
                    </div>
                  </div>
                </div>

                {/* 4. DOCTOR NETWORK VIEW */}
                <div
                  className={`absolute inset-0 p-8 flex flex-col justify-center transition-all duration-500 ${activeService === 3 ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8 pointer-events-none"}`}
                >
                  <div className="relative w-full max-w-sm mx-auto aspect-video bg-slate-800 rounded-xl overflow-hidden border border-amber-500/30 shadow-2xl">
                    {/* Fake Video Feed */}
                    <div className="absolute inset-0 bg-gradient-to-b from-transparent to-slate-900/90 z-10 flex flex-col justify-end p-4">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-slate-300 border-2 border-amber-500"></div>
                        <div>
                          <p className="text-white text-sm font-bold">
                            Dr. Sarah Jenning
                          </p>
                          <p className="text-slate-400 text-xs">
                            Neurologist • Mayo Clinic
                          </p>
                        </div>
                      </div>
                      <div className="absolute top-4 right-4 flex gap-2">
                        <div className="px-2 py-1 bg-red-500/80 text-white text-[10px] font-bold rounded uppercase animate-pulse">
                          Live
                        </div>
                      </div>
                    </div>
                    {/* Abstract doctor shape */}
                    <div className="absolute inset-0 flex items-center justify-center opacity-30">
                      <Video size={64} className="text-slate-400" />
                    </div>
                  </div>
                </div>
              </div>

              {/* Bottom decorative bar of card */}
              <div
                className={`h-1.5 w-full bg-gradient-to-r transition-all duration-500 ${services[activeService].color}`}
              ></div>
            </div>
          </div>
        </div>
      </div>

      {/* Animation Styles */}
      <style>{`
        @keyframes loading {
          0% { width: 0% }
          100% { width: 84% }
        }
      `}</style>
    </section>
  );
};

export default ServicesSection;
